info/modules/news/__init__.py
from flask import Blueprint

news_blue = Blueprint("news_blue",__name__,url_prefix="/news")

from . import views

info/modules/news/views.py
#目的是跳转到新闻详情页
from . import news_blue
from flask import  request,current_app,jsonify,abort,session,render_template,abort,g
from info.models import News,User,tb_user_collection,Comment,CommentLike

from info import response_code,constants,db
from info.utils.comment import user_login


@news_blue.route("/comment_lickcount",methods=["POST"])
# 有点赞的情况，获取评论的id和新闻id
# 确定请求方式。post请求，接受参数
@user_login
def comment_lickcount():
#     首先判断用户是否存在，基于评论的，评论已经判断完毕，这里可判断，可不判断
    user = g.user
    print(user)
    if not user:
        return jsonify(erron=response_code.RET.DBERR, errsmg="用户未登录")
#     接受参数comment_id和news_id
    comment_id=request.json.get("comment_id")
    news_id = request.json.get("news_id")
    action= request.json.get("action")
# 在钱端一定是bool值用来判断，点赞还是取消点赞
#     判断参数是否存在
    if not all([comment_id,news_id,action]):
        return jsonify(erron=response_code.RET.PARAMERR, errsmg="缺少参数")
    # 查看数据库中lick_count是否存在,存在表示点赞,不存在表示没有点赞,取出和评论相关联的对象,在点出来
    comment=[]
    try:
        comment = Comment.query.filter(Comment.id == comment_id, Comment.news_id == news_id).all()
    except Exception as e:
        abort(405)
    # 将评论从数据库中取出来,然后判断评论是否存在(因为很可能不存在)
    if not comment:
        return jsonify(errno=response_code.RET.NODATA, errmsg='评论不存在')


# comment.like_count:不能直接查询获取用户点过赞的额评论

    comment_like_count = CommentLike.query.filter(CommentLike.user_id==user.id,CommentLike.comment_id ==comment_id).first()
    # 查询是该用户的评论的对象

    if action == "add":
        if not comment_like_count:
    #     如果点赞的数量在数据库中不存在,没有人点在(也就是可以点赞)
    # 将数据添加到数据库还需要将数据库中的所有对应必须加入的字段放进去
            comment_like_count = CommentLike()
            comment_like_count.user_id = user.id
            comment_like_count.comment_id = comment_id
            db.session.add(comment_like_count)
            Comment.like_count += 1
        try:
           db.session.commit()
        except Exception as e:
           db.session.rollback()
           current_app.logger.error(e)
           return jsonify(errno=response_code.RET.DBERR, errmsg='操作失败')
       #    每次添加完数据以后都需要将点击量同步到数据库,添加到数据库后代表点赞成功,所以要天际数据库后统计数据
       # else:
       #     不能取消(不对数据库进行操作)     e
    #     如果数据库中存在,1\不能在点了
    else:
        if comment_like_count:
           db.session.delete(comment_like_count)
           Comment.like_count -= 1
           try:
               db.session.commit()
           except Exception as e:
               db.session.rollback()
               current_app.logger.error(e)
               return jsonify(errno=response_code.RET.DBERR, errmsg='操作失败')

    return jsonify(errno=response_code.RET.OK, errmsg='操作成功')
#         如果不是添加,查看数据库中是否存在点赞,存在就取消,不存在添加



@news_blue.route("/news_comment",methods=["POST"])
@user_login
def news_comment():
#     首先判断用户存在，才可以评论
    user = g.user
    if not user:
        return jsonify(erron=response_code.RET.DBERR,errsmg="用户未登录")
#     form表但提交是post请求，用后台传递数据通过form
#     获取前端传过来的数据
    news_id = request.json.get("news_id")
#     获取评论信息

    comment_context = request.json.get("comment")
    parent_id = request.json.get("parent_id")
    if not all([news_id,comment_context]):
        return jsonify(erron = response_code.RET.PARAMERR,errsmg="缺少参数")
#     如果新闻存在
# 将新闻放入评论的数据库中
#     获取新闻数据
    news_id =int(news_id)



    try:
        news = News.query.filter(News.id==news_id).all()
        print(news)

        # print(comment.content)
        # 将获取的评论信息放入Comment的和use_id相同的表里面，是个列表
    #     谁评论的就将用户和评论信息加入到数据库
    # 列表对象没有append，还可以采用赋值的方式放入数据库
    # 当前用户当前评论
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=response_code.RET.DBERR, errmsg='操作失败')
    if not news:
        return jsonify(errno=response_code.RET.DBERR, errmsg='新闻不存在')

    comment = Comment()


    comment.user_id = user.id
    comment.news_id = news_id
    comment.content = comment_context
    # parent_id = int(parent_id)
    #         数据库中少了一个点赞条数
    if parent_id :
        comment.parent_id = parent_id


    print(comment)
    # 当前评论完毕，
    # 回复评论
    # 如果有父parent——id表示是回复评论
    # 后台需要将comment新增数据传过去
    # 将从前台获取的数据放入数据库

    try:
        db.session.add(comment)
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        current_app.logger.error(e)
        return jsonify(errno=response_code.RET.DBERR, errmsg='评论失败')

    return jsonify(errno=response_code.RET.OK, errmsg='操作成功',data=comment.to_dict())
    #    首先确定回复评论就是在页面中多了一个用户和用户的评论。在数据库中用户和父用户是多多多的关系，如果有ｐａｒｅｎｔ存在就代表是回父，如果不存在就是
    # 评论
@news_blue.route("/news_collect",methods=["POST"])
# 收藏新闻id,需要前端给我传过来新闻id和d
# iffuse收藏
# 之所以将收藏和取消收藏在写一个函数定义,是因为需要和 用户关联的数据库中存入数据,所以修改数据库需要用到post请求
# 所以用ajax,news_id,action
#
@user_login
def news_collect():
    # user_id=session.get("user_id")
    # nick_name=session.get("nick_name")
    user = g.user
    if not all([user]) :
        return jsonify(erron=response_code.RET.SESSIONERR ,errmsg="用户未登录")

    news_id = request.json.get("news_id")

    action= request.json.get("action")

    if not all([news_id, action]):
        # 虽然写上了取消ｉｄ和取消参数，参数限定的了自己执行自己的
        return jsonify(erron=response_code.RET.PARAMERR, ermasg="缺少参数")
#     在用户存在的情况下,从数据库中取出来和浏览器给我发过来的新闻id,,并将数据加入和数据库相关的库中
#     antion值必须是cancel_collect',collect
#     所以ａｎｔｉｏｎ必须在cancel_collect',collect，其它的不行
# 在数据库搜索 以后,将数据展现在模板上面
    if action not in ['cancel_collect','collect']:
        return jsonify(erron=response_code.RET.PARAMERR, ermasg="参数错误")
    if action =='collect':
        news= []

        # user = []
        try:
            news = News.query.get(news_id)


            # user = User.query.get(user_id)
        except Exception as e:
            current_app.logger.error(e)
            abort(405)

        if news not in  user.collection_news:


            user.collection_news.append(news)

        else:

            user.collection_news.remove(news)  #     每次只能添加一次数据
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            current_app.logger.error(e)


            return jsonify(errno=response_code.RET.DBERR, errmsg='操作失败')




    return jsonify(errno=response_code.RET.OK, errmsg='操作成功')


#         收藏写完以后,写取消收藏
# 因为都是post的请求,接受参数,可以将两者放在一个路由里面
# 第一步获取取消以及取消新闻id的参数
# 判断参数是否存在,
# 判断用户是否存在
# 用户和收藏是否存在,
# 如果存在可以取消收藏
# 如何取消收藏，就是用户点击的新闻id,将ｉｄ从数据库中删除
# 理解因为news_id只是个接受用户收藏和取消的容器，两者可以通过ajax异步执行，增加新闻id3和取消id5
# （不知道对不对）




# 只有用户是登录的状态才可以有收藏的功能

# @news_blue.route("/detail/<int:news_id>",methods=["GET"])
@news_blue.route("/detail",methods=["GET"])
# def detail(news_id):
@user_login
def detail():
    # 根据前台需要,需要导入用户名,判断是get请求查寻数据直接将数据return就可以
    news_id=request.args.get("news.id:")

    user = g.user
    print(user)
    # if not user:
    #     return jsonify(errno=response_code.RET.SESSIONERR, errmsg='用户未登录')
    # 这里不应该,判断用户不存在,因为不关用户存不存在,就需要显示当前的页面(不等录的也应该可以看见)
    news=[]
    news_comments_count=[]
    try:
        news = News.query.filter(News.id ==news_id).first()


    except Exception as e:
        print(news)
        current_app.logger.error(e)
        # 判断数据库中的新闻是否存在,系统原因,报505,注意点news是对象需要将其变成字典
        # 当前页面只有一条数据,所以不需要遍历

    news_clicks = []
    # user=[]
    try:
        news_clicks = News.query.order_by(News.clicks.desc()).limit(constants.CLICK_RANK_MAX_NEWS)
        # user = User.query.filter(User.id==user_id).first()
        print(user)
    except Exception as e:
        current_app.logger.error(e)
        #    威慑么是这样写,不应该是显示的是当前页的数据的点击量码?威慑么还是按着新闻点击量来()

    if not all([news,news_clicks]):
        abort(505)
    # 如果新闻存在,将数据发送到html中
    # 最初时的状态新闻的点击是0
    # 新闻点击量是 News.clicks,每运行一次,该新闻点击一次

    news.clicks +=1
    # 将累计的点击量放入数据库中
    try:
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        current_app.logger.error(e)

    is_collected=False
    # if user_id:

    comment = []
    if user:
        if news in user.collection_news:
            is_collected = True
    #首先评论的内容显示在detail的页面里面，的内容
    # 从数据库中抽取数据，数据库是comment表
    try:
        comment = Comment.query.filter(Comment.news_id==news_id).order_by(Comment.create_time.desc()).all()
    # order_by(Comment.create_time.desc()).all()为什么按时间排序呢?
    # 因为获取出来的评论不是只有1条,用户评论过的数据全部都要显示在页面上面,并且按时间顺序排列
    # 这里不能使用get了,get只能取来对应的对象,不是集合
    # 评论的数据在用户存在的时候可以展示,在用户不存在的时候页要显示
    except Exception as e:
        current_app.logger.error(e)

    # 在detail.html页面需要将评论信息,从数据库拿出来,并发送给html以及点赞的数量
    # 点赞和取消点赞还需要定地来嗯个布尔值,传递给html
    # 展示出评论中的点赞数量(点赞或者没有点赞是根据bool值来判断
    # 将所有用户的点赞都取出来
    comment_line=[]
    if user:
        try:
            comment_like = CommentLike.query.filter(CommentLike.user_id ==user.id ).all()
            # 接下来将页面上排序的评论和用户点赞一一对应起来
            # 取出来所有被用户点赞的评论id
            comment_line = [ CommentLike.comment_id for comment_value in comment_like]
        except Exception as e:
            print(news)
            current_app.logger.error(e)
    # 点过赞的用户都取出来了,点郭赞的评论取出来了
    # 将所有的评论的id都取出来看看评论是否在用户点赞的评论id
    # is_like = False
    # if [user, comment.context]:
    #
    #     if comment.id in comment_line:
    #     #     评论的id在用户点过赞的id里面,就显示高亮,判断高亮的是is_like
    #         is_like=True
    # # 赞存在的前提是用户和评论都存在
    # else:
    #
    #     is_like = False
    # 为了方便使用model中的字典数据,将所有对象集合遍历出来,转化成字典的形式,最后将所有的字典放在打列表中转化成列表字典
    comment_list_dict=[]
    for comment in comment:
        comment_dict = comment.to_dict()
        comment_dict['is_like'] = False
        if comment.id in comment_line:
            comment_dict['is_like'] = True
        comment_list_dict.append(comment_dict)

    context={
        "user_id":user,

        "news":news.to_dict(),
        "news_clicks":news_clicks,
        'is_collected': is_collected,
        "comment":comment_list_dict,

    }

    # 从页面上
    # 从页面上可知需要动态传入点击量,detail.html据库中取出来
    return render_template("news/detail.html",context=context)

info/modules/user/__init__.py
from flask import Blueprint

user_blue = Blueprint("user",__name__,url_prefix="/user")

from . import views
# passport_blue = Blueprint("passport",__name__,url_prefix="/passport")
#
# from . import views

info/modules/user/views.py
#用户中心必须是要在用那户登录的状态
from . import user_blue
from flask import g,jsonify,render_template,redirect,url_for,request,current_app,session
from info.utils.comment import user_login
from info.utils.image_storage import storage

# from flask import  request,current_app,jsonify,abort,session,render_template,abort,g
from info.models import db
#
from info import response_code
#
@user_blue.route("/user_pic",methods=["GET","POST"])
@user_login

def user_pic():
#     点击图片时是get请求,返回的是user_pic表单
    user = g.user
    if not user:
        return redirect(url_for("user/user_center"))
        #     首先点击基本信息,会向浏览器发送请求,返回一个表格
    if request.method == "GET":
        context = {
            'user': user,
        }
        return render_template('news/user_pic_info.html', context=context)
    if request.method =="POST":
        avatar = request.files.get("avatar")
#        图片可以用files直接获取表单里面图片的值
        if not avatar:
#             如果图片不存在,应该给个默认头像
           avatar =
#         如果存在,将图片上传到七牛云
        avatar_qiniu = sorted(avatar)
#     上传后将图片路径存入到数据库中



# 基本信息页
@user_blue.route("/user_infomation",methods=["GET","POST"])
@user_login
def user_infomation():
#     判断用户是否存在
     user = g.user
     if not user:
         return redirect(url_for("user/user_center"))
#     首先点击基本信息,会向浏览器发送请求,返回一个表格
     if request.method=="GET":
         context = {
             'user': user,
         }
         return render_template('news/user_base_info.html', context=context)
#      接下来是post请求,接受用户上传的基本信息
     if request.method =="POST":
#          接受参数signature,nick_name,gender
        signature= request.json.get("signature")

        nick_name=request.json.get("nick_name")

        gender=request.json.get("gender")
#         判断数据是否存
        if not all([ signature,nick_name,gender]):
            return jsonify(errno=response_code.RET.DBERR, errmsg="缺少参数")
#         如果参数存在,将数据存入数据库,并将数据发送给前端,渲染出来,还应该放在redis中一份,做状态保持

        user.signature =  signature
        user.nick_name = nick_name
        user.gender = gender
        try:

            db.session.commit()

        except Exception as e:
            db.session.rollback()
            return jsonify(errno=response_code.RET.DBERR, errmsg="操作失败")
        # 当用户点击保存以后,应该跳转到显示修改后的信息的页面

        session["nick_name"]=nick_name

     # return redirect(url_for('user.user_center'))
     return jsonify(errno=response_code.RET.OK, errmsg='修改基本资料成功')





@user_blue.route("/user_center")
@user_login
def user_center():
    # 首先判断用户是否存在
    # 判断请求方式是get请求
    # 如果用户存在返回user.html页面
    # 效果是当点击名字或者头像时跳转到我命名的路径上面
    user = g.user
    if not user:
        return redirect(url_for('index.index'))
    context={
        'user':user,
    }
    return render_template("news/user.html",context=context)

info/templates/news/dase.html
{% extends "news/index.html" %}
{% block title %}
    <title>首页-新经资讯</title>
{% endblock title %}

{% block main %}
    <script type="text/javascript" src="../../static/news/js/index.js"></script>
{#     <script type="text/javascript" src="../../static/news/js/main.js"></script>#}
{% endblock main %}

{% block body %}
    <div class="header_con">
        <div class="header">
            <a href="#" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
            <ul class="menu fl">
                {% for category in context.category%}
                {% if loop.index==1 %}
                <li class="active" data-cid="{{category.id}}"><a href="javascript:;">{{category.name}}</a></li>
                {% else %}
                <li data-cid="{{category.id}}"><a href="javascript:;">{{category.name}}</a></li>
                {% endif %}
                {% endfor %}
                <!--<li data-cid="2"><a href="javascript:;">股市</a></li>-->
                <!--<li data-cid="3"><a href="javascript:;">债市</a></li>-->
                <!--<li data-cid="4"><a href="javascript:;">商品</a></li>-->
                <!--<li data-cid="5"><a href="javascript:;">外汇</a></li>-->
                <!--<li data-cid="6"><a href="javascript:;">公司</a></li>-->
            </ul>


            <!-- 用户登录后显示下面，隐藏上面 -->

            {% if context.user %}
            <div class="user_login fr">
                <img src="{% if context.user.avatar_url %}{{ context.user.avatar_url }}{% else %}../../static/news/images/person01.png{% endif %}"  class="lgin_pic">
                <a href="{{ url_for('user.user_center') }}">{{context.user.nick_name}}</a>
                <a href="javascript:;" onclick="logout()">退出</a>
            </div>
            {% else %}
                <div class="user_btns fr">
                    <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock body %}

{% block conter %}
      <ul class="list_con fl">
{#            这里将来使用js动态的渲染#}
        </ul>
{% endblock conter %}
 <ul class="list_con fl">
{#            这里将来使用js动态的渲染#}
        </ul>
{% block rank %}
    <div class="rank_con fr">
            <div class="rank_title">
                <h3>点击排行</h3>
            </div>
    <ul class="rank_list">
                {% for news in context.news_clicks %}
                <li><span class="{{loop.index | rank}}">{{loop.index}}</span><a href="#">{{news.title}}</a></li>
                {% endfor %}
                <!--<li><span class="first">1</span><a href="#">势如破竹！人民币再度连闯四道关口 在岸、离岸双双升破6.42</a></li>-->
                <!--<li><span class="second">2</span><a href="#">凛冬已至，还有多少银行人在假装干银行</a></li>-->
                <!--<li><span class="third">3</span><a href="#">人民日报：部分城市楼市放松限制引关注，楼市调控不会“拉抽屉”</a></li>-->
                <!--<li><span>4</span><a href="#">势如破竹！人民币再度连闯四道关口 在岸、离岸双双升破6.42</a></li>-->
                <!--<li><span>5</span><a href="#">凛冬已至，还有多少银行人在假装干银行</a></li>-->
                <!--<li><span>6</span><a href="#">人民日报：部分城市楼市放松限制引关注，楼市调控不会“拉抽屉”</a></li>-->
            </ul>
{% endblock rank %}

info/templates/news/detail.html
{% extends "news/index.html" %}
{% block title %}
     <title>文章详情页</title>
{% endblock title%}
 {% block main %}
        <script type="text/javascript" src="../../static/news/js/detail.js"></script>
       <script type="text/javascript" src="../../static/news/js/main.js"></script>
{% endblock main %}

{% block body %}
            <div class="header_con">
            <div class="header">
            <!-- 用户登录后显示下面，隐藏上面 -->
            <div class="user_login fr">
                <img src="../../static/news/images/person01.png" class="lgin_pic">
                {% if  context.user_id %}

                    <div class="user_login fr">
                        <img src="{% if context.user_id.avatar_url %}{{ context.user_id.avatar_url }}{% else %}../../static/news/images/person01.png{% endif %}" class="lgin_pic">
                        <a href="{{ url_for('user.user_center') }}">{{ context.user_id.nick_name }}</a>
                        <a href="javascript:;" onclick="logout()">退出</a>
                    </div>
                {% else %}
                    <div class="user_btns fr">
                        <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
                    </div>
                {% endif %}

            </div>
            </div>
    </div>
{% endblock body %}
    

        {% block conter %}
            <div class="detail_con fl">

            <h3>{{ context.news.title }}</h3>
            <div class="detail_about clearfix">
                <span class="time_souce fl">{{ context.news.create_time }}来源: {{ context.news.source }}</span>
                <span class="comment fr">{{ context.news.comments_count }}</span>
{#                是点击量#}
            </div>

            <p class="summary">
                {{ context.news.digest }}
            </p>

            <h4>{{ context.news.title  }}</h4>
            <p>{{ context.news.content|safe }}</p>
{#            <p>#}
{#            港股方面今天表现强劲，开年以来的上涨势头仍然延续，恒指收涨1.8%创下收盘新高。此前恒指的峰值是在2007年10月份盘中触及的31958点。</p>#}
{#<p>#}
{#今天恒指51支成份股中，42支上涨，7支下跌，对恒指贡献最大的个股包括建设银行上涨3.7%，腾讯控股上涨2.5%，香港交易所上涨5.9%，工商银行上涨3.3%，中国平安上涨2.8%。</p>#}
{#<p>#}
{#2018年的前15日，恒生指数已经上涨了4.75%，恒生国企指数上涨了6.50%。</p>#}
{#<p>#}
{#兴业证券张忆东在最新报告中表示，港股作为全球估值洼地，不论是分红率高的价值股还是业绩确定的成长股都受益于新一年中资和海外机构资金的重新布局。他维持2016年以来对“港股牛市”的判断，认为2018年港股市场会出现核心资产驱动的慢牛、长牛行情。他还预计今年下半年港股将迎来牛市主升浪。</p>#}
{#<p>#}
{#与A股交相呼应，港股内房股今天也是集体爆发的行情。万科企业涨9.2%，融创中国涨3.7%，碧桂园涨3%，中国恒大涨1.6%。</p>#}
{#<p>#}
{#此外，中国平安港股股价再创历史新高，盘中一度触及91.00港元。中国平安在A股市场今天也一度上涨近2%，离历史高点仅一步之遥，但收盘时回落，最终收涨0.2%。</p>#}
{#<p>#}
{#昨天晚间，中国平安公布2017年保费收入，全年该集团控股子公司平安财险、平安人寿、平安养老、平安健康原保险合同保费收入分别为2159.84亿元、3689.34亿元、175.6亿元及21.47亿元，合计约6046.26亿元人民币，同比增28.9%。除此以外，市场传出中国平安旗下的陆金所将于4月分拆于香港上市，估值达600亿美元。</p>#}
            <a href="javascript:;" class="collected block-center" data-newid="{{ context.news.id }}" style="display: {% if context.is_collected %} block
            {% else %} none {% endif %};"><span class="out">已收藏</span><span class="over">取消收藏</span></a>

            <a href="javascript:;" class="collection block-center" data-newid="{{ context.news.id }}" style="display: {% if context.is_collected %} none
            {% else %} block {% endif %};">收藏</a>

        {% if not context.user_id %}
        <div class="comment_form_logout">
            登录发表你的评论

        </div>
        {% else %}
        <form action="" class="comment_form" data-newsid="{{ context.news.id }}">
            <div class="person_pic">
                <img src="{% if context.user_id.avatar_url %}{{ context.user_id.avatar_url }}{% else %} ../../static/news/images/person01.png {% endif %}"alt="用户图标">
            </div>
            <textarea placeholder="请发表您的评论" class="comment_input"></textarea>
            <input type="submit" name="" value="评 论" class="comment_sub">
        </form>
        {% endif %}


        <div class="comment_count">
            {{ context.news.comments_count }}条数据
        </div>

        <div class="comment_list_con">
            {% for comment in context.comment %}
            <div class="comment_list">
                <div class="person_pic fl">
                    <img src="{% if comment.user.avatar_url %}
                            {{ comment.user.avatar_url }}
                        {% else %}
                            ../../static/news/images/person01.png
                        {% endif %} " alt="用户图标">
                </div>
                <div class="user_name fl">{{ comment.user.nick_name }}</div>
                <div class="comment_text fl">
                   {{ comment.content }}
                </div>
                 {% if comment.parent %}
                        <div class="reply_text_con fl">
                            <div class="user_name2">{{ comment.parent.user.nick_name }}</div>
                            <div class="reply_text">
                                {{ comment.parent.content }}
                            </div>
                        </div>
                    {% endif %}
                    <div class="comment_time fl">{{ comment.create_time }}</div>
{#用户点赞#}
                <a href="javascript:;" class=" comment_up {%if comment.is_like %} has_comment_up{% endif %} fr"
                    data-commentid="{{ comment.id }}" data-newsid="{{ comment.news_id }}" data-likecount="{{ comment.like_count }}">
                     {% if comment.like_count > 0 %}
                        {{ comment.like_count }}
                    {% else %}
                    赞
                {% endif %}
                </a>
{#     用户点赞       #}

                <a href="javascript:;" class="comment_reply fr">回复</a>

                <from class="reply_form fl" data-commentid="{{ comment.id }}" data-newsid="{{ context.news.id }}">
                    <textarea  class="reply_input"></textarea>
                    <input type="submit" name="" value="回复" class="reply_sub fr">
                    <input type="reset" name="" value="取消" class="reply_cancel fr">
                </from>

            </div>
               {% endfor %}
        </div>
            </div>


        {% endblock conter %}
        {% block rank %}
            <div class="rank_con fr">
            <div class="author_card">
                <a href="#" class="author_pic"><img src="../../static/news/images/user_pic.png" alt="author_pic"></a>
                <a href="#" class="author_name">张大山</a>
                <div class="author_resume">张大山的简介,张大山</div>
                <div class="writings"><span>总篇数</span><b>23</b></div>
                <div class="follows"><span>粉丝</span><b>36</b></div>
                <a href="javascript:;" class="focus fr">关注</a>
                <a href="javascript:;" class="focused fr"><span class="out">已关注</span><span class="over">取消关注</span></a>
            </div>
            <div class="rank_title">
                <h3>点击排行</h3>
            </div>
            <ul class="rank_list">
                {% for news in context.news_clicks %}
                    <li><span class="{{ loop.index | rank }}">{{ loop.index }}</span><a href="#">{{ news.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
        {% endblock rank %}

info/templates/news/user.html
{% extends "news/dase.html" %}
	<title>用户中心</title>

{% block main %}
	<script type="text/javascript" src="../../static/news/js/jquery.form.min.js"></script>
{% endblock main %}

{% block body %}
	<div class="header_con">
		<div class="header">
			<a href="#" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
			<div class="user_login fr" style="display: block;">
				<img src={% if context.user.avatar_url %}{{ context.user.avatar_url }}{% else %}
                "../../static/news/images/user_pic.png"
                {% endif %} alt="用户图片">
				<a href="{{ url_for('user.user_center') }}">{{ context.user.nick_name }}</a>
				<a href="#">退出</a>
			</div>
		</div>
	</div>
	
	<div class="conter_con">
		<div class="user_menu_con fl">
			<div class="user_center_pic">
				<img {% if context.user.avatar_url %}{{ context.user.avatar_url }}{% else %}} src="../../static/news/images/user_pic.png"{% endif %} alt="用户图片">
			</div>
			<div class="user_center_name">{{ context.user.nick_name }}</div>

			<ul class="option_list">
				<li class="active"><a href="{{ url_for('user.user_infomation') }}" target="main_frame">基本资料</a></li>
				<li><a href="user_pic_info.html" target="main_frame">头像设置</a></li>
				<li><a href="../../static/news/html/user_follow.html" target="main_frame">我的关注</a></li>
				<li><a href="../../static/news/html/user_pass_info.html" target="main_frame">密码修改</a></li>
				<li><a href="../../static/news/html/user_collection.html" target="main_frame">我的收藏</a></li>
				<li><a href="../../static/news/html/user_news_release.html" target="main_frame">新闻发布</a></li>
				<li><a href="../../static/news/html/user_news_list.html" target="main_frame">新闻列表</a></li>
			</ul>
		</div>

		<div class="user_con fr">
			<iframe src="{{ url_for('user.user_infomation') }}" frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>
		</div>		
	</div>
   {% endblock body %}